# Configuration for BlackBox used in .vagrantfile

# HOSTS
# ---------------------------------------------------
# VM domain
domain: blackbox.app
# Private VM IP
ip: 192.168.33.10

# MySQL @root password
mysql_root_pw: "root"

# List of virtual hosts
hosts:
  -
    url: 'example-nopath.app'
    path: ''
  -
    url: 'example-subpath.app'
    path: 'path/subpath'

# VIRTUALBOX CONFIG
# ---------------------------------------------------
cpu: 2
memory: 1024
