# Configuration for BlackBox used in .vagrantfile

# HOSTS
# ---------------------------------------------------
# VM domain
domain: blackbox.dev
# Private VM IP
ip: 192.168.33.10

# List of virtual hosts
hosts:
  # -
  #   url: testhost1.dev
  #   path: '/'
  # -
  #   url: testhost2.dev
  #   path: public

# VIRTUALBOX CONFIG
# ---------------------------------------------------
cpu: 2
memory: 1024
