# Configuration for BlackBox executed by used in .vagrantfile

# HOSTS
# ---------------------------------------------------
# VM domain
domain: blackbox.dev
# Private VM IP
ip: 192.168.33.12

# List of virtual hosts
hosts:
  -
    url: host1.dev
    path: '/'
  -
    url: host2.dev
    path: public
  -
    url: host3.dev
    path: public

# VIRTUALBOX CONFIG
# ---------------------------------------------------
cpu: 2
memory: 1024
